name: Tests-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16


    - name: Test
      env:
        BOT_TOKEN: ${{ github.BOT_TOKEN }}
      run: go test -v ./...
