name: Tests-windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      env:
          BOT_TOKEN: ${{ github.BOT_TOKEN_WINDOWS }}
      run: echo "$BOT_TOKEN" >> tests\config && go test -v .\...
